# Generated by Django 6.0.5 on 2026-05-08 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('bird', 'bird')], default='cat'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('description', models.CharField()),
                ('image', models.CharField()),
                ('price', models.IntegerField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_products', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
