# Generated by Django 6.0.5 on 2026-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_animal_type_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clinic',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
