# Generated by Django 6.0.5 on 2026-05-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_customuser_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Name',
            new_name='animal_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Name',
            new_name='product_name',
        ),
    ]
