# Generated by Django 6.0.5 on 2026-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_products_description_alter_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(),
        ),
    ]
